name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Docker run
        run: docker compose up -d

      - name: Test with Gradle
        id: test
        run: ./gradlew test
        if: always()
